
services:
  mydb:
    image: mydb 
    ports:
      - "5432:5432"  
    volumes:
      - ./init-db/init:/docker-entrypoint-initdb.d
      -  pgdata:/var/lib/postgresql/data
    networks:
      - net
  backend:
    image: petsclinic-backend 
    environment:
     - SPRING_PROFILES_ACTIVE=postgres
    ports:
      - "8080:8080" 
    depends_on:
      - mydb
         
    networks:
      - net

  frontend:
    image: petsclinic-frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
         
    networks:
      - net
  
networks:
   net:
    driver: bridge
volumes:
   pgdata:
