FROM postgres:latest

# Optional: Copy custom initialization scripts
# COPY init.sql /docker-entrypoint-initdb.d/


ENV POSTGRES_USER=petclinic
ENV POSTGRES_DB=petclinic
ENV POSTGRES_PASSWORD=petclinic

# Expose the default PostgreSQL port
EXPOSE 5432
